build:webapi:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - pwd
    - cd dotnetbackend
    - pwd
    - dotnet --version
    - dotnet --info
    - dotnet build --verbosity detailed

pages:
  image: node
  before_script:
    - pwd
  script:
    - cd angularfrontend
    - npm --version
    - date
    - yarn install
    - date
    - yarn run ng build --aot=true --prod --build-optimizer --verbose --progress=true --delete-output-path --extract-licenses --subresource-integrity --stats-json --output-path=public --base-href="/ondotnet/"
    - date
    - du -sh public/
    - mv public ../public
    - ls -a
    - pwd
    - cd ..
    - ls -a
    - pwd
  artifacts:
    paths:
      - public

